version: '3.8'

networks:
  public-network:
    driver: bridge

services:
  api:
    container_name: codechat_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8084:8084
    volumes:
      - instances_connected:/codechat/instances
      - api_logs:/codechat/logs
    env_file:
      - ./.env
    networks:
      - public-network

volumes:
  instances_connected:
  api_logs:
